apiVersion: apps/v1
kind: Deployment
metadata:
  name: rapidcompetitions
  labels:
    app: rapidcompetitions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rapidcompetitions
  template:
    metadata:
      labels:
        app: rapidcompetitions
    spec:
      containers:
        - name: rapidcompetitions
          image: cryptic0053/rapidcompetitions:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
