apiVersion: v1
kind: Service
metadata:
  name: rapidcompetitions-service
spec:
  type: NodePort
  selector:
    app: rapidcompetitions
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007
